# -*- coding: utf-8 -*-
"""Mini project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bkp8_ASjN9xsl3fUCe7gZUm7l_t0vcQc
"""

import os

USER_DATA_DIR = "user_data"
os.makedirs(USER_DATA_DIR, exist_ok=True)

def register_user(username, password):
    user_dir = os.path.join(USER_DATA_DIR, username)
    os.makedirs(user_dir, exist_ok=True)
    with open(os.path.join(user_dir, "password.txt"), "w") as password_file:
        password_file.write(password)

def login(username, password):
    user_dir = os.path.join(USER_DATA_DIR, username)
    password_file = os.path.join(user_dir, "password.txt")
    if os.path.exists(password_file):
        with open(password_file, "r") as password_file:
            stored_password = password_file.read()
        if password == stored_password:
            return user_dir
    return None

def create_diary_entry(user_dir, title, date, content):
    entry_filename = os.path.join(user_dir, f"{date}.txt")
    with open(entry_filename, "w") as entry_file:
        entry_file.write(content)

def decrypt_diary_entry(entry_filename):
    with open(entry_filename, "r") as entry_file:
        content = entry_file.read()
    return content


def search_diary_entries(user_dir, keyword):
    entries = []
    keyword = keyword.lower()
    for entry_filename in os.listdir(user_dir):
        if entry_filename.endswith(".txt"):
            entry_path = os.path.join(user_dir, entry_filename)
            content = decrypt_diary_entry(entry_path).lower()
            if keyword in content:
                entries.append((entry_filename, content))
    return entries

def main():
    while True:
        print("1. Register\n2. Login\n3. Exit")
        choice = input("Select an option: ")

        if choice == "1":
            username = input("Enter your username: ")
            password = input("Enter your password: ")
            register_user(username, password)
            print("User registered successfully.")
        elif choice == "2":
            username = input("Enter your username: ")
            password = input("Enter your password: ")
            user_dir = login(username, password)
            if user_dir:
                while True:
                    print("1. Create Diary Entry\n2. Search Entries\n3. Logout")
                    user_choice = input("Select an option: ")
                    if user_choice == "1":
                        title = input("Enter the title: ")
                        date = input("Enter the date: ")
                        content = input("Enter the content: ")
                        create_diary_entry(user_dir, title, date, content)
                        print("Diary entry created.")
                    elif user_choice == "2":
                        keyword = input("Enter the keyword to search: ")
                        entries = search_diary_entries(user_dir, keyword)
                        if entries:
                            for entry_filename, content in entries:
                                print(f"Entry: {entry_filename}\n{content}\n")
                        else:
                            print("No matching entries found.")
                    elif user_choice == "3":
                        print("Logged out.")
                        break
                    else:
                        print("Invalid option.")
            else:
                print("Login failed. Check your username and password.")
        elif choice == "3":
            print("Exiting program.")
            break
        else:
            print("Invalid option.")

if __name__ == "__main__":
    main()