# -*- coding: utf-8 -*-
"""Minor_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YbMxkSt2fMl3_WHFizbaz3WFQrI4C60a
"""

class CollegeManagementSystem:
    def __init__(self):
        self.students = {}
        self.courses = {"PY11":"PYTHON","JA12":"JAVA","DS13":"DATA STRUCTURES","JS14":"JAVASCRIPT"}
        self.registrations = {}

    def register_student(self, student_id, name, dob):
        self.students[student_id] = {'name': name, 'dob': dob}
        print(f"Student {name} (ID: {student_id}) has been registered.\n")

    def display_students(self):
        print("Registered Students:")
        for student_id, student_info in self.students.items():
            print(f"ID: {student_id}, Name: {student_info['name']}, DOB: {student_info['dob']}")

    def update_student_info(self, student_id, name, dob):
        if student_id in self.students:
            self.students[student_id] = {'name': name, 'dob': dob}
            print(f"Student {name} (ID: {student_id}) information has been updated.")
        else:
            print(f"Student with ID {student_id} not found.")

    def display_courses(self):
        print("55Available Courses:")
        for course_code, course_title in self.courses.items():
            print(f"Code: {course_code}, Title: {course_title}")

    def add_course(self, course_code, course_title):
        self.courses[course_code] = course_title
        print(f"Course '{course_title}' ({course_code}) has been added.")


    def enroll_student(self, student_id, course_code):
        if student_id in self.students and course_code in self.courses:
            if student_id not in self.registrations:
                self.registrations[student_id] = []
            if course_code not in self.registrations[student_id]:
                self.registrations[student_id].append(course_code)
                print(f"Student (ID: {student_id}) has registered for course '{self.courses[course_code]}'.")
            else:
                print(f"Student (ID: {student_id}) is already registered for this course.")
        else:
            print("Invalid student ID or course code.")

    def view_registrations(self):
        print("Course Registrations:")
        for student_id, courses in self.registrations.items():
            student_name = self.students.get(student_id, {}).get('name')
            print(f"Student: {student_name} (ID: {student_id})")
            for course_code in courses:
                course_title = self.courses.get(course_code)
                print(f"  --- Course: {course_title} ({course_code})")

# College Management System menu
college_system = CollegeManagementSystem()

while True:
    print("\nCollege Management System Menu:")
    print("1. Register Student")
    print("2. Display Students")
    print("3. Update Student Information")
    print("4. Display Courses")
    print("5. Add Courses")
    print("6. Enroll Student in Course")
    print("7. View Registrations")
    print("8. Exit\n")

    choice = input("Enter your choice (1-8): ")
    print("\n")

    if choice == "1":
        student_id = int(input("Enter Student ID: "))
        name = input("Enter Student Name: ")
        dob = input("Enter Date of Birth: ")
        college_system.register_student(student_id, name, dob)

    elif choice == "2":
        college_system.display_students()

    elif choice == "3":
        student_id = int(input("Enter Student ID to update: "))
        name = input("Enter updated name: ")
        dob = input("Enter updated Date of Birth: ")
        college_system.update_student_info(student_id, name, dob)

    elif choice == "4":
        college_system.display_courses()

    elif choice == "5":
        course_code = input("Enter Course Code: ")
        course_title = input("Enter Course Title: ")
        college_system.add_course(course_code, course_title)


    elif choice == "6":
        student_id = int(input("Enter Student ID: "))
        course_code = input("Enter Course Code: ")
        college_system.enroll_student(student_id, course_code)

    elif choice == "7":
        college_system.view_registrations()

    elif choice == "8":
        print("Exiting College Management System.")
        break

    else:
        print("Invalid choice. Please enter a valid option (1-8).")

choice = input("Enter your choice (1-8): ")

type(choice)