# -*- coding: utf-8 -*-
"""G28_HOUSING_DATA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ul33TQYQ7v0sVuCx2NlaKGbB_YVVsRDW

Import The Libraries And Dataset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Display Top 5 Rows of The Dataset"""

housing  = pd.read_csv('/content/housing.csv')
housing.head()

"""
Check The Last 5 Rows of The Dataset"""

housing.tail()

"""Find Shape of Our Dataset (Number of Rows And Number of Columns)"""

housing.shape

print("Number of Rows:", housing.shape[0])
print("Number of Columns:", housing.shape[1])

"""Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement"""

housing.info()

"""Check Null Values In The Dataset"""

housing.isnull().sum()

"""null values will be replaced with the mean of the column"""

housing = housing.fillna(housing.mean())

housing.isnull().sum()

"""
Check For Duplicate Data"""

housing_dup = housing.duplicated().any()
print(housing_dup)

"""using encoder to make the string to int values"""

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
housing['ocean_proximity']= label_encoder.fit_transform(housing['ocean_proximity'])

housing['ocean_proximity'].unique()

housing

housing["ocean_proximity"].value_counts()

"""Get Overall Statistics About The Dataset"""

housing.describe()

housing.columns

p= housing['ocean_proximity'].value_counts()
print(p)

sns.countplot(data=housing,x=housing['median_house_value'])

"""barplot"""

sns.countplot(data=housing,x=housing['ocean_proximity'])

sns.displot(housing['ocean_proximity'],bins=20)
plt.show()

sns.countplot(x="households", hue="ocean_proximity", data=housing)
plt.legend(labels = ['householders','place'])
plt.show()

"""histogram plot

"""

housing['ocean_proximity'].hist()

housing.hist(bins=50, figsize=(20,15))
plt.savefig("attribute_histogram_plots.png")
plt.show()

