# -*- coding: utf-8 -*-
"""miniprojectmanisairam

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wKE5tfR23fl5aZ9UdvavAmQ_kIetT1qZ
"""

tasks = []

#functions
def add_task():
    title = input("Enter task title: ")
    description = input("Enter task description: ")
    status = "Incomplete"
    tasks.append({"title": title, "description": description, "status": status})
    print("Task added successfully!")

# Function to display tasks
def display_tasks():
    if not tasks:
        print("No tasks found.")
    else:
        print("Tasks:")
        for idx, task in enumerate(tasks):
            print(f"{idx + 1}. Title: {task['title']}, Description: {task['description']}, Status: {task['status']}")
def complete_task():
    display_tasks()
    try:
        task_number = int(input("Enter the task number to mark as complete: "))
        if 1 <= task_number <= len(tasks):
            tasks[task_number - 1]["status"] = "Complete"
            print("Task marked as complete.")
        else:
            print("Invalid task number.")
    except ValueError:
        print("Invalid input. Please enter a valid task number.")
def delete_task():
    display_tasks()
    try:
        task_number = int(input("Enter the task number to delete: "))
        if 1 <= task_number <= len(tasks):
            deleted_task = tasks.pop(task_number - 1)
            print(f"Deleted task: Title: {deleted_task['title']}, Description: {deleted_task['description']}, Status: {deleted_task['status']}")
        else:
            print("Invalid task number.")
    except ValueError:
        print("Invalid input. Please enter a valid task number.")
while True:
    print("\nTo-Do List Manager Menu:")
    print("1. Add Task")
    print("2. Display Tasks")
    print("3. Mark Task as Complete")
    print("4. Delete Task")
    print("5. Quit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_task()
    elif choice == "2":
        display_tasks()
    elif choice == "3":
        complete_task()
    elif choice == "4":
        delete_task()
    elif choice == "5":
        break
    else:
        print("Invalid choice. Please select a valid option.")

